# Use postgres/example user/password credentcials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: !abcd1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080